<?php

namespace Internit\AcompanhamentoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tupi\AdminBundle\Entity\CrudRepository;

/**
 * AcompanhamentoEtapaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcompanhamentoRepository extends CrudRepository
{
	public function listItens($key = 'item', $first = 0, $max = 10) 
	{
		$builder = $this->createQueryBuilder($key);
		$builder->setFirstResult( $first );
		$builder->setMaxResults( $max );
		$builder->join("{$key}.imovel", "i");
		$builder->join("i.status", "s");
		$builder->where("s.id != :id");
		$builder->setParameter("id", "5");		
		//$builder->orderBy("{$key}.id","DESC");
		$builder->orderBy("{$key}.position","ASC");
		return $builder;
	}
	
    public function findByImovelUrl($url)
    {
        $qb = $this->createQueryBuilder('a')
        ->join("a.imovel", "i")
        ->where("i.url = :url")
        ->setParameter("url", $url);
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    public function carregamentoSobDemandaAcompanhamentos($page = 0){
    	$qb = $this->createQueryBuilder("i")
    	->select('i')
		->where('i.status=:status')
		->setParameter("status", 1)
    	->orderBy("i.position", "ASC")
    	->setMaxResults(3)
    	->setFirstResult($page);
    	return $qb->getQuery()->getResult();
    }
}