<?php

namespace Internit\AcompanhamentoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tupi\AdminBundle\Entity\CrudRepository;

/**
 * AcompanhamentoEtapaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocoRepository extends CrudRepository
{    
    public function listForm($filter = 0) { 	
        $qb = $this->createQueryBuilder('o')
            ->join('o.acompanhamento', 'a')
            ->where('a.id = :filter')
            ->setParameter('filter', $filter)
            ->orderBy("o.id","DESC")
            ->getQuery()
            ->getResult();
        return $qb;
    }
}