<?php

namespace Internit\AcompanhamentoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tupi\AdminBundle\Entity\CrudRepository;

/**
 * EtapaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapaRepository extends CrudRepository
{   
	public function listItens($key = 'item', $first = 0, $max = 10) {
		$builder = parent::listItens($key, $first, $max);
		$builder->resetDQLPart('orderBy');
		$builder->orderBy("{$key}.position","ASC");

		return $builder;
	}
	
    public function getLast()
    {
        $qb = $this->createQueryBuilder('p')
        ->select('p')
        ->orderBy('p.id', 'DESC')
        ->setMaxResults(1);
         
        return $qb->getQuery()->getSingleResult();
    }
    
    public function lastPosition()
    {
        $qb = $this->createQueryBuilder('e')
        ->select('e.position')
        ->orderBy('e.position', 'DESC')
        ->setMaxResults(1);
         
        return $qb->getQuery()->getSingleResult();
    }
    
    public function getCount()
    {
        $qb = $this->createQueryBuilder('p')
        ->select('count(p.id)');
    
        return $qb->getQuery()->getSingleScalarResult();
    }
}