<?php

namespace Internit\AcompanhamentoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tupi\AdminBundle\Entity\CrudRepository;

/**
 * GaleriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaRepository extends CrudRepository
{ 
    public function listForm($filter = 0) {
        $qb = $this->createQueryBuilder('o')
        ->join('o.bloco', 'b')
        ->where('b.id = :filter')
        ->setParameter('filter', $filter)
        ->orderBy("o.id","DESC")
        ->getQuery()
        ->getResult();
        return $qb;
    }
       
    public function getLast()
    {
        $qb = $this->createQueryBuilder('p')
        ->select('p')
        ->orderBy('p.id', 'DESC')
        ->setMaxResults(1);
         
        return $qb->getQuery()->getSingleResult();
    }
    
    public function lastPosition()
    {
        $qb = $this->createQueryBuilder('e')
        ->select('e.position')
        ->orderBy('e.position', 'DESC')
        ->setMaxResults(1);
         
        return $qb->getQuery()->getSingleResult();
    }
    
    public function getCount()
    {
        $qb = $this->createQueryBuilder('p')
        ->select('count(p.id)');
        
        return $qb->getQuery()->getSingleScalarResult();
    }
}