<?php

namespace Tupi\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Tupi\AdminBundle\Entity\CrudRepository;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends CrudRepository
{
}
