<?php

namespace Internit\RandomChatBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tupi\AdminBundle\Entity\CrudRepository;

/**
 * RandomChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RandomChatRepository extends CrudRepository
{
   public function getChatTurn()
   {
   		$chatTurn = $this->getEntityManager()->createQueryBuilder()
   		->select('t')
   		->from('InternitRandomChatBundle:RandomChatTurn', 't');
   		
   		return  $chatTurn->getQuery()->getSingleResult();
   }
   
   public function getChatLinks()
   {
	   	$chatTurn = $this->getEntityManager()->createQueryBuilder()
	   	->select('l')
	   	->from('InternitRandomChatBundle:RandomChatLinks', 'l');
	   	 
	   	return  $chatTurn->getQuery()->getResult();
   }
   
    public function getCount()
    {
        $qb = $this->createQueryBuilder('p')
        ->select('count(p.id)');
    
        return $qb->getQuery()->getSingleScalarResult();
    }
}
