parameters:
    database_driver:   pdo_mysql
    database_host:     db01.lab58.internit.br
    database_port:     null
    database_name:     tupicms
    database_user:     labuser
    database_password: labpass

    mailer_transport:  mail
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            pt-BR
    secret:            34411e1310e3947931014a8c6308a22abb

    debug_toolbar:          true
    debug_redirects:        false
    use_assetic_controller: true
