<?php

namespace Internit\ImovelBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tupi\AdminBundle\Entity\CrudRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ImovelStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImovelStatusRepository extends CrudRepository
{
	public function findAllVisible($limit = null)
	{
		$qb = $this->createQueryBuilder('s')
		->select('s')
		->join('s.imoveis', 'i')
		->where('i.destaque = 1')
		->andWhere('i.visible = 1')
		->orderBy('i.position', 'ASC');
	
		if(!is_null($limit)){
			$qb->setMaxResults($limit);
		}
		 
		return $qb->getQuery()->getResult();
	}
}