<?php

namespace Internit\ImovelBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tupi\AdminBundle\Entity\CrudRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ImovelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImovelMakersRepository extends CrudRepository
{
	
}