<?php

namespace Internit\NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tupi\AdminBundle\Entity\CrudRepository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends CrudRepository
{  
	public function create(Newsletter $cr)
	{
		$cr->setCreatedAt(new \DateTime());
		$cr->setName($cr->getName());
		$cr->setEmail($cr->getEmail());
		$this->getEntityManager()->persist($cr);
		$this->getEntityManager()->flush();
	}
	
    public function getContacts()
    {
    	return $this->findAll();
    } 
}