<?php

namespace Internit\AtasBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tupi\AdminBundle\Entity\CrudRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AtasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtasRepository extends CrudRepository
{				
	public function findAll()
	{
		$qb = $this->createQueryBuilder("i")
		->select('i')
		->orderBy('i.dataVigente', 'DESC');
		return $qb->getQuery()->getResult();
	}
		
	public function findByTitulo($tag)
	{		
		$qb = $this->createQueryBuilder("i")
		->select('i')
		->orderBy('i.dataVigente', 'DESC')
		->where('i.tags LIKE :tag')
		->setParameter("tag", '%'.$tag.'%');	
		return $qb->getQuery()->getResult();
	}		
}	
