<?php

namespace Tupi\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tupi\AdminBundle\Entity\CrudRepository;

/**
 * MediaFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaFileRepository extends CrudRepository
{
	public function remove($obj)
	{
		$this->_em->remove($obj->getMedia());
	}
	
	public function findByMimeType($type)
	{
	    $qb = $this->createQueryBuilder('i')
	    ->select('i')
	    ->where('i.mimeType LIKE :type')
	    ->setParameter('type', '%'.$type.'%');
	
	    return $qb->getQuery()->getResult();
	}
}
